name: test-on-ubuntu
on: [push]
jobs:
  compile-program:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Check submodules presence
        run:
          pwd
          ls /home/runner/work/E5150/
          pwd
          ls /home/runner/work/E5150/E5150
          pwd
          ls /home/runner/work/E5150/E5150/third-party
          pwd
          ls /home/runner/work/E5150/E5150/third-party/catch2
          pwd
          ls /home/runner/work/E5150/E5150/third-party/spdlog
          pwd

      - name: Compiling the project
        run: make -j4
        working-directory: /home/runner/work/E5150/E5150
      

  compile-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursives
      - run: make -j4
        working-directory: /home/runner/work/E5150/E5150

  test:
    runs-on: ubuntu-latest
    needs: [compile-program, compile-tests]
    steps:
      - run: pwd
