name: test-on-ubuntu
on: [push]
jobs:
  compile-program:
    runs-on: ubuntu-latest
    steps:
      - run: ls /home/runner/work/E5150/
      - run: ls /home/runner/work/E5150/E5150
      - run: ls /home/runner/work/E5150/E5150/third-party/catch2
      - run: ls /home/runner/work/E5150/E5150/third-party/spdlog

      - name: Compiling the project
        run: make -j4
        working-directory: /home/runner/work/E5150/E5150
      

  compile-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursives
      - run: make -j4
        working-directory: /home/runner/work/E5150/E5150

  test:
    runs-on: ubuntu-latest
    needs: [compile-program, compile-tests]
    steps:
      - run: pwd
