name: test-on-ubuntu
on: [push]
jobs:
  compile-program:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Repository
        uses: actions/checkout@v2
          with:
            submodules: 'recursives'
      - name: Compiling the program
        run: make -j4
          working-directory: /home/runner/work/E5150/E5150

  compile-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursives'
      - run: cd /home/runner/work/E5150/E5150
      - run: make -j4

  test:
    runs-on: ubuntu-latest
    needs: [compile-program, compile-tests]
    steps:
      - run: pwd
