name: test-on-ubuntu
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
