name: test-on-ubuntu
on: [push]
jobs:
  compile-program:
    container: ghcr.io/dridrilabastos/e5150/ci
    steps:
      - name: Getting repository sources
        uses: actions/checkout@v2

      - name: Compiling the project
        run: make -j$(sysctl -n hw.ncpu)
        working-directory: /home/runner/work/E5150/E5150

  compile-tests:
    container: ghcr.io/dridrilabastos/e5150/ci
    steps:
      - uses: actions/checkout@v2
      - run: make -j$(sysctl -n hw.ncpu)
        working-directory: /home/runner/work/E5150/E5150

  test:
    runs-on: ubuntu-latest
    needs: [compile-program, compile-tests]
    steps:
      - run: pwd
